### ISSUE TITLE
It doesn't seem to work with Pycharm Pro/ Missing info

### ISSUE THREAD

**Issue by Marcel176** [AntonShuvaev/intellij-datagraph#5]
What to do to display such graph? There is no additional icon. Clicking on the file is just displaying the file. Please add info how to use it. Or it doesn't seem to work with Pycharm Pro.

**Comment by AntonShuvaev** [comment]
There should be buttons for 'Editor', 'Editor and Preview', and 'Preview' on the tabs panel (see the screenshot). If these buttons are missing, it likely means the plugin was unable to initialize the internal JCEF browser. One possible reason for this issue is the use of a Java runtime that lacks JCEF support.
<img width="1163" alt="Screenshot 2024-02-15 at 14 22 54" src="https://github.com/AntonShuvaev/intellij-datagraph/assets/25157138/91195953-4f64-4367-9885-c3b0e58d489a">
